namespace DO;

public enum TypeOfCall
{
    CARDIAC_ARREST,
    DIFFICULTY_BREATHING,
    CAR_ACCIDENT,
    STROKE,
    SEVERE_BLEEDING,
    UNCONSCIOUS_PERSON,
    BURN_INJURY,
    CHOKING,
    FALL_FROM_HEIGHT,
    DIABETIC_EMERGENCY,
    SEIZURE,
    ALLERGIC_REACTION,
    CHILDBIRTH,
    POISONING,
    ASSAULT_INJURY,
    DROWNING,
    ELECTRIC_SHOCK,
    HEAD_INJURY,
    BROKEN_BONE,
    HEAT_STROKE
};

public enum TypeOfTreatmentEnding {HOSPITAL_ADMISSION, STAY_AT_HOME,DEAD , EXPIRED, UNMATCHED };

public enum TypeOfDistance {AIR, WALK, DRIVE };

public enum Role {ADMINISTRATOR,STANDARD};
public enum Status { WAITING, BEING_HANDELED, BEING_HANDELED_IN_RISK }

public enum Options
{
    EXIT,
    VOLUNTEER_MENU,
    ASSIGNMENT_MENU,
    CALL_MENU,
    INITIALIZE,
    PRINT_DATA,
    CONFIG_MENU,
    RESET_DB_CONFIG
}
public enum CallStatus { OPEN, BEING_HANDELED, CLOSED, OUT_OF_DATE, OPEN_IN_RISK, BEING_HANDELED_IN_RISK }
public enum AssignmentStatus { OPEN, BEING_HANDELED, CLOSED, OUT_OF_DATE, OPEN_IN_RISK, BEING_HANDELED_IN_RISK, COMPLETED }
public enum SpecificOptions
{
    EXIT,
    CREATE,
    READ,
    READ_ALL,
    UPDATE,
    DELETE,
    DELETE_ALL,
    ASSIGN_VOLUNTEER_TO_CALL, 
    UNMATCH_VOLUNTEER_FROM_CALL
}
public enum configOptions
{
    EXIT,
    ADVANCE_SYSTEM_CLOCK_BY_MINUTE,
    ADVANCE_SYSTEM_CLOCK_BY_HOUR,
    ADVANCE_SYSTEM_CLOCK_BY_DAY,
    ADVANCE_SYSTEM_CLOCK_BY_YEAR,
    DISPLAY_CURRENT_TIME,
    CHANGE_VALUE,
    DISPLAY_CURRENT_VALUE,
    RESET_CONFIG
}



